# Generated by Django 2.1.3 on 2019-07-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile_pic',
        ),
    ]
